# Generated by Django 3.1.5 on 2021-02-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210204_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_type',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
