# Generated by Django 3.1.5 on 2021-02-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210210_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoRequester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('message', models.TextField(null=True)),
            ],
        ),
    ]
